#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
#Smaller binary size for release binaries
# https://kotlinlang.org/docs/whatsnew2220.html#smaller-binary-size-for-release-binaries
#kotlin.native.binary.smallBinary=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true